/** @jsx React.DOM */
jest.dontMock('../components/MenuBar.js');

describe('MenuBarRenders', function() {
  it('is an example MenuBar rendering', function() {
    var React = require('react/addons');
    var MenuBar = require('../components/MenuBar.js');
    var TestUtils = React.addons.TestUtils;

    //mock data
    var data = [
      {name: "Home"},
      {name: "Messages"},
      {name: "live"}
    ];

    //Render menubar
    var menubar = TestUtils.renderIntoDocument(
      <MenuBar data={data}></MenuBar>
    );

    //Varify that data object is being generated by component
    var ul = TestUtils.findRenderedDOMComponentWithTag(menubar, 'ul');
    expect(ul.getDOMNode().textContent).toContain("Home");

  });
});




























// describe('menu-component', function() {
//   it('Menu should display at least one item', function() {
//     var React = require('react/addons');
//     var menu = require('../menu-components');
//     var TestUtils = React.addons.TestUtils;
//
//
//     // Verify menu items displays
//     // var menubar = TestUtils.renderIntoDocument(
//     //   <MenuBar>
//     // );
//
//     // Verify list items are dendered
//     // var list = TestUtils.findRenderedDOMComponentWithTag(menubar, 'li');
//     // expect(list.getDOMNode().textContent).toEqual(''));
//
//
//   });
//});
